# Site settings
title: Canary
email: info@canarytech.ca
description: > # this means to ignore newlines until "baseurl:"
  Canary is professional expertise in e-commerce services 
  enable our clients to build successful e-commerce businesses and branding.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.canarytech.ca" # the base hostname & protocol for your site

# User setting
owner: Canary
email: info@canarytech.ca
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Canary Tech

# API settings
google_api_key:

# Build settings
markdown: kramdown
